spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mossol

server:
  port: 8181

# slack integration
slack:
  enable: true
  token: <defined as environment variable in the production machine>

# line integration
line:
  secret: <defined as environment variable in the production machine>
  token: <defined as environment variable in the production machine>

# central dogma
centraldogma:
  hosts:
  - mossol.net:7373

retrofit:
  baseUrl: https://api.line.me
  connectionTimeOutMills: 5000
  maxRetry: 3

service:
  enabled:
    line: true
